package gui.admin.finance;

public class FinanceDashboardPanel extends javax.swing.JPanel {

    private final AdminFinancePortal financePortal;
    
    public FinanceDashboardPanel(AdminFinancePortal financePortal) {
        this.financePortal = financePortal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHRDashboard = new javax.swing.JPanel();
        jPanelDepartmentsBox = new javax.swing.JPanel();
        jLabelTotalDepartments = new javax.swing.JLabel();
        jLabelInsertDepartments = new javax.swing.JLabel();
        jPanelDateAndTimeBox = new javax.swing.JPanel();
        jLabelInsertDateAndTime = new javax.swing.JLabel();
        jLabelDateAndTIme = new javax.swing.JLabel();
        jPanelEmployeesCountBox1 = new javax.swing.JPanel();
        jLabelTotalEmployeesCount1 = new javax.swing.JLabel();
        jLabelInsertEmployeesCount1 = new javax.swing.JLabel();
        jPanelPendingTickets = new javax.swing.JPanel();
        jLabelPendingTickets = new javax.swing.JLabel();
        jLabelPendingFinanceTickets = new javax.swing.JLabel();
        jLabelHelloAdmin = new javax.swing.JLabel();
        jLabelDashboardSmall = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHRDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHRDashboard.setPreferredSize(new java.awt.Dimension(1120, 750));
        jPanelHRDashboard.setLayout(null);

        jPanelDepartmentsBox.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDepartmentsBox.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelDepartmentsBox.setLayout(null);

        jLabelTotalDepartments.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalDepartments.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalDepartments.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTotalDepartments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTotalDepartments.setText("Total Departments");
        jPanelDepartmentsBox.add(jLabelTotalDepartments);
        jLabelTotalDepartments.setBounds(20, 0, 240, 50);

        jLabelInsertDepartments.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInsertDepartments.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabelInsertDepartments.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInsertDepartments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsertDepartments.setText("0");
        jPanelDepartmentsBox.add(jLabelInsertDepartments);
        jLabelInsertDepartments.setBounds(20, 50, 380, 100);

        jPanelHRDashboard.add(jPanelDepartmentsBox);
        jPanelDepartmentsBox.setBounds(90, 440, 420, 160);

        jPanelDateAndTimeBox.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDateAndTimeBox.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelDateAndTimeBox.setLayout(null);

        jLabelInsertDateAndTime.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInsertDateAndTime.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelInsertDateAndTime.setForeground(new java.awt.Color(33, 105, 84));
        jLabelInsertDateAndTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsertDateAndTime.setText("January 1, 2025 12:00:00");
        jPanelDateAndTimeBox.add(jLabelInsertDateAndTime);
        jLabelInsertDateAndTime.setBounds(20, 60, 380, 60);

        jLabelDateAndTIme.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDateAndTIme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDateAndTIme.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDateAndTIme.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDateAndTIme.setText("Date and Time");
        jPanelDateAndTimeBox.add(jLabelDateAndTIme);
        jLabelDateAndTIme.setBounds(20, 0, 140, 50);

        jPanelHRDashboard.add(jPanelDateAndTimeBox);
        jPanelDateAndTimeBox.setBounds(600, 240, 420, 160);

        jPanelEmployeesCountBox1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmployeesCountBox1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelEmployeesCountBox1.setLayout(null);

        jLabelTotalEmployeesCount1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotalEmployeesCount1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTotalEmployeesCount1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTotalEmployeesCount1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTotalEmployeesCount1.setText("Total Employees Count");
        jPanelEmployeesCountBox1.add(jLabelTotalEmployeesCount1);
        jLabelTotalEmployeesCount1.setBounds(20, 0, 240, 50);

        jLabelInsertEmployeesCount1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInsertEmployeesCount1.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabelInsertEmployeesCount1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInsertEmployeesCount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsertEmployeesCount1.setText("0");
        jPanelEmployeesCountBox1.add(jLabelInsertEmployeesCount1);
        jLabelInsertEmployeesCount1.setBounds(20, 50, 380, 100);

        jPanelHRDashboard.add(jPanelEmployeesCountBox1);
        jPanelEmployeesCountBox1.setBounds(90, 240, 420, 160);

        jPanelPendingTickets.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPendingTickets.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelPendingTickets.setLayout(null);

        jLabelPendingTickets.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPendingTickets.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabelPendingTickets.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPendingTickets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPendingTickets.setText("0");
        jPanelPendingTickets.add(jLabelPendingTickets);
        jLabelPendingTickets.setBounds(20, 50, 380, 100);

        jLabelPendingFinanceTickets.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPendingFinanceTickets.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPendingFinanceTickets.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPendingFinanceTickets.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPendingFinanceTickets.setText("Pending Finance Tickets");
        jPanelPendingTickets.add(jLabelPendingFinanceTickets);
        jLabelPendingFinanceTickets.setBounds(20, 0, 240, 50);

        jPanelHRDashboard.add(jPanelPendingTickets);
        jPanelPendingTickets.setBounds(600, 440, 420, 160);

        jLabelHelloAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHelloAdmin.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabelHelloAdmin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHelloAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelHelloAdmin.setText("Hello, Admin!");
        jPanelHRDashboard.add(jLabelHelloAdmin);
        jLabelHelloAdmin.setBounds(30, 30, 190, 29);

        jLabelDashboardSmall.setText("Finance Dashboard");
        jPanelHRDashboard.add(jLabelDashboardSmall);
        jLabelDashboardSmall.setBounds(30, 60, 110, 16);

        add(jPanelHRDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDashboardSmall;
    private javax.swing.JLabel jLabelDateAndTIme;
    private javax.swing.JLabel jLabelHelloAdmin;
    private javax.swing.JLabel jLabelInsertDateAndTime;
    private javax.swing.JLabel jLabelInsertDepartments;
    private javax.swing.JLabel jLabelInsertEmployeesCount1;
    private javax.swing.JLabel jLabelPendingFinanceTickets;
    private javax.swing.JLabel jLabelPendingTickets;
    private javax.swing.JLabel jLabelTotalDepartments;
    private javax.swing.JLabel jLabelTotalEmployeesCount1;
    private javax.swing.JPanel jPanelDateAndTimeBox;
    private javax.swing.JPanel jPanelDepartmentsBox;
    private javax.swing.JPanel jPanelEmployeesCountBox1;
    private javax.swing.JPanel jPanelHRDashboard;
    private javax.swing.JPanel jPanelPendingTickets;
    // End of variables declaration//GEN-END:variables
}