package gui.admin.hr;

import gui.employee.EmployeePortal;
import gui.login.LoginPortal;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class AdminHRPortal extends javax.swing.JFrame {
    private final Color defaultPanelColor = Color.WHITE;
    private final Color hoverPanelColor = new Color(33, 105, 84);
    private final HRDashboardPanel hrDashboardPanel;
    private final TicketsPanel ticketsPanel;
    private final ViewTicketPanel viewTicketPanel;
    private final EmployeesPanel employeesPanel; 
    private final CreateEmployeePanel createEmployeePanel;
    private final ViewEmployeePanel viewEmployeePanel;
    private final AttendancePanel attendancePanel;
    private final ViewAttendancePanel viewAttendancePanel;
    private final LeavesPanel leavesPanel;
    private final ViewLeavePanel viewLeavePanel;
    private final OvertimePanel overtimePanel;
    private final ViewOvertimePanel viewOvertimePanel;
    

    public AdminHRPortal() {
        setFlatLafUI();
        this.setTitle("MotorPH HR Portal");
        setWindowIcon();
        hrDashboardPanel = new HRDashboardPanel(this);
        ticketsPanel = new TicketsPanel(this);
        viewTicketPanel = new ViewTicketPanel(this);
        employeesPanel = new EmployeesPanel(this);
        createEmployeePanel = new CreateEmployeePanel(this);
        viewEmployeePanel = new ViewEmployeePanel(this);
        attendancePanel = new AttendancePanel(this);
        viewAttendancePanel = new ViewAttendancePanel(this);
        leavesPanel = new LeavesPanel(this);
        viewLeavePanel = new ViewLeavePanel(this);
        overtimePanel = new OvertimePanel(this);
        viewOvertimePanel = new ViewOvertimePanel(this);
        initComponents();
        addHooverEffectToTabs();
        addPanels();
        this.setLocationRelativeTo(null);
    }
    
    private void setFlatLafUI() {
        try {
            com.formdev.flatlaf.FlatIntelliJLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf.");
        }
    }
    
    private void setWindowIcon() {
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/title-green-motor-logo.png"));
            this.setIconImage(icon);
        } catch (Exception e) {
            System.err.println("Icon image not found.");
        }
    }
    
    public JPanel getPanelParentCard() {
        return this.jPanelParentCard;
    }
    
    private void addPanels() {
        getPanelParentCard().add(hrDashboardPanel, "HRDashboard");
        getPanelParentCard().add(ticketsPanel, "Tickets");
        getPanelParentCard().add(viewTicketPanel, "ViewTicket");
        getPanelParentCard().add(employeesPanel, "Employees");
        getPanelParentCard().add(createEmployeePanel, "CreateEmployee");
        getPanelParentCard().add(viewEmployeePanel, "ViewEmployee");
        getPanelParentCard().add(attendancePanel, "Attendance");
        getPanelParentCard().add(viewAttendancePanel, "ViewAttendance");
        getPanelParentCard().add(leavesPanel, "Leaves");
        getPanelParentCard().add(viewLeavePanel, "ViewLeave");
        getPanelParentCard().add(overtimePanel, "Overtime");
        getPanelParentCard().add(viewOvertimePanel, "ViewOvertime");
    }
    
    private void addHooverEffectToTabs() {
        addHoverEffect(jLabelHRDashboard, jPanelHRDashboard);
        addHoverEffect(jLabelEmployeePortal, jPanelEmployeePortal);
        addHoverEffect(jLabelTickets, jPanelTickets);
        addHoverEffect(jLabelEmployees, jPanelEmployees);
        addHoverEffect(jLabelAttendance, jPanelAttendance);
        addHoverEffect(jLabelLeaves, jPanelLeaves);
        addHoverEffect(jLabelOvertime, jPanelOvertime);
    }

    private void addHoverEffect(JLabel label, JPanel panel) {
        Font originalFont = label.getFont();

        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel.setBackground(hoverPanelColor);
                label.setFont(originalFont.deriveFont(Font.BOLD));
                label.setForeground(Color.WHITE);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel.setBackground(defaultPanelColor);
                label.setFont(originalFont);
                label.setForeground(Color.BLACK);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWhiteMain = new javax.swing.JPanel();
        jPanelBlueNavigationMenu = new javax.swing.JPanel();
        jPanelTickets = new javax.swing.JPanel();
        jLabelTickets = new javax.swing.JLabel();
        jPanelHRDashboard = new javax.swing.JPanel();
        jLabelHRDashboard = new javax.swing.JLabel();
        jPanelEmployees = new javax.swing.JPanel();
        jLabelEmployees = new javax.swing.JLabel();
        jPanelEmployeePortal = new javax.swing.JPanel();
        jLabelEmployeePortal = new javax.swing.JLabel();
        jPanelOvertime = new javax.swing.JPanel();
        jLabelOvertime = new javax.swing.JLabel();
        jPanelAttendance = new javax.swing.JPanel();
        jLabelAttendance = new javax.swing.JLabel();
        jLabelMotorPH = new javax.swing.JLabel();
        jPanelLeaves = new javax.swing.JPanel();
        jLabelLeaves = new javax.swing.JLabel();
        jLabelMorPHLogo = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jPanelParentCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelWhiteMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelWhiteMain.setForeground(new java.awt.Color(255, 255, 255));
        jPanelWhiteMain.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanelWhiteMain.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanelWhiteMain.setName(""); // NOI18N
        jPanelWhiteMain.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanelWhiteMain.setLayout(null);

        jPanelBlueNavigationMenu.setBackground(new java.awt.Color(218, 242, 228));
        jPanelBlueNavigationMenu.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanelBlueNavigationMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTickets.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTickets.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTickets.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTickets.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTickets.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTickets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTickets.setText("Tickets");
        jLabelTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTicketsMouseClicked(evt);
            }
        });
        jPanelTickets.add(jLabelTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 40));

        jPanelHRDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHRDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHRDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHRDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHRDashboard.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHRDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHRDashboard.setText("Dashboard");
        jLabelHRDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHRDashboardMouseClicked(evt);
            }
        });
        jPanelHRDashboard.add(jLabelHRDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelHRDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 40));

        jPanelEmployees.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmployees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmployees.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmployees.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEmployees.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmployees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmployees.setText("Employees");
        jLabelEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmployeesMouseClicked(evt);
            }
        });
        jPanelEmployees.add(jLabelEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 40));

        jPanelEmployeePortal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmployeePortal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmployeePortal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmployeePortal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEmployeePortal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmployeePortal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmployeePortal.setText("Employee Portal");
        jLabelEmployeePortal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelEmployeePortalMouseMoved(evt);
            }
        });
        jLabelEmployeePortal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmployeePortalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEmployeePortalMouseEntered(evt);
            }
        });
        jLabelEmployeePortal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelEmployeePortalKeyPressed(evt);
            }
        });
        jPanelEmployeePortal.add(jLabelEmployeePortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelEmployeePortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 40));

        jPanelOvertime.setBackground(new java.awt.Color(255, 255, 255));
        jPanelOvertime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelOvertime.setBackground(new java.awt.Color(255, 255, 255));
        jLabelOvertime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelOvertime.setForeground(new java.awt.Color(0, 0, 0));
        jLabelOvertime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOvertime.setText("Overtime");
        jLabelOvertime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOvertimeMouseClicked(evt);
            }
        });
        jPanelOvertime.add(jLabelOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 180, 40));

        jPanelAttendance.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAttendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAttendance.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAttendance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAttendance.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAttendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAttendance.setText("Attendance");
        jLabelAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAttendanceMouseClicked(evt);
            }
        });
        jPanelAttendance.add(jLabelAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 180, 40));

        jLabelMotorPH.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMotorPH.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabelMotorPH.setForeground(new java.awt.Color(33, 105, 84));
        jLabelMotorPH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMotorPH.setText("MotorPH");
        jPanelBlueNavigationMenu.add(jLabelMotorPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 40));

        jPanelLeaves.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLeaves.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLeaves.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLeaves.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLeaves.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLeaves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLeaves.setText("Leaves");
        jLabelLeaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLeavesMouseClicked(evt);
            }
        });
        jPanelLeaves.add(jLabelLeaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelLeaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, 40));

        jLabelMorPHLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green-motor-logo.png"))); // NOI18N
        jPanelBlueNavigationMenu.add(jLabelMorPHLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 40));

        jLabelLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green-log-out-icon.png"))); // NOI18N
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
        });
        jPanelBlueNavigationMenu.add(jLabelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, -1, -1));

        jPanelWhiteMain.add(jPanelBlueNavigationMenu);
        jPanelBlueNavigationMenu.setBounds(10, 10, 220, 750);

        jPanelParentCard.setBackground(new java.awt.Color(204, 255, 255));
        jPanelParentCard.setMaximumSize(new java.awt.Dimension(1120, 750));
        jPanelParentCard.setMinimumSize(new java.awt.Dimension(1120, 750));
        jPanelParentCard.setPreferredSize(new java.awt.Dimension(1120, 750));
        jPanelParentCard.setLayout(new java.awt.CardLayout());
        jPanelWhiteMain.add(jPanelParentCard);
        jPanelParentCard.setBounds(240, 10, 1120, 750);

        getContentPane().add(jPanelWhiteMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLeavesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLeavesMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Leaves");
    }//GEN-LAST:event_jLabelLeavesMouseClicked

    private void jLabelAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAttendanceMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Attendance");
    }//GEN-LAST:event_jLabelAttendanceMouseClicked

    private void jLabelOvertimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOvertimeMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Overtime");
    }//GEN-LAST:event_jLabelOvertimeMouseClicked

    private void jLabelEmployeePortalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEmployeePortalKeyPressed

    private void jLabelEmployeePortalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEmployeePortalMouseEntered

    private void jLabelEmployeePortalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalMouseClicked
        // TODO add your handling code here:
        EmployeePortal employeePortal = new EmployeePortal();
        employeePortal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEmployeePortalMouseClicked

    private void jLabelEmployeePortalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEmployeePortalMouseMoved

    private void jLabelEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmployeesMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Employees");
    }//GEN-LAST:event_jLabelEmployeesMouseClicked

    private void jLabelTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTicketsMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Tickets");
    }//GEN-LAST:event_jLabelTicketsMouseClicked

    private void jLabelHRDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHRDashboardMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "HRDashboard");
    }//GEN-LAST:event_jLabelHRDashboardMouseClicked

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to log out?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            LoginPortal loginPortal = new LoginPortal();
            loginPortal.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabelLogOutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAttendance;
    private javax.swing.JLabel jLabelEmployeePortal;
    private javax.swing.JLabel jLabelEmployees;
    private javax.swing.JLabel jLabelHRDashboard;
    private javax.swing.JLabel jLabelLeaves;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelMorPHLogo;
    private javax.swing.JLabel jLabelMotorPH;
    private javax.swing.JLabel jLabelOvertime;
    private javax.swing.JLabel jLabelTickets;
    private javax.swing.JPanel jPanelAttendance;
    private javax.swing.JPanel jPanelBlueNavigationMenu;
    private javax.swing.JPanel jPanelEmployeePortal;
    private javax.swing.JPanel jPanelEmployees;
    private javax.swing.JPanel jPanelHRDashboard;
    private javax.swing.JPanel jPanelLeaves;
    private javax.swing.JPanel jPanelOvertime;
    private javax.swing.JPanel jPanelParentCard;
    private javax.swing.JPanel jPanelTickets;
    private javax.swing.JPanel jPanelWhiteMain;
    // End of variables declaration//GEN-END:variables
}
