package gui.admin.it;

import gui.employee.EmployeePortal;
import gui.login.LoginPortal;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class AdminITPortal extends javax.swing.JFrame {
    private final Color defaultPanelColor = Color.WHITE;
    private final Color hoverPanelColor = new Color(33, 105, 84);
    private final ITDashboardPanel itDashboardPanel;
    private final TicketsPanel ticketsPanel;
    private final ViewTicketPanel viewTicketPanel;
    private final AccountsPanel accountsPanel;
    private final ViewAccountPanel viewAccountPanel;
    private final SecurityPanel securityPanel;
    
    public AdminITPortal() {
        setFlatLafUI();
        this.setTitle("MotorPH IT Portal");
        setWindowIcon();
        itDashboardPanel = new ITDashboardPanel(this);
        ticketsPanel = new TicketsPanel(this);
        viewTicketPanel = new ViewTicketPanel(this);
        accountsPanel = new AccountsPanel(this);
        viewAccountPanel = new ViewAccountPanel(this);
        securityPanel = new SecurityPanel(this);
        initComponents();
        addHooverEffectToTabs();
        addPanels();
        this.setLocationRelativeTo(null);
    }
    
    private void setFlatLafUI() {
        try {
            com.formdev.flatlaf.FlatIntelliJLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf.");
        }
    }
    
    private void setWindowIcon() {
        try {
            Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/title-green-motor-logo.png"));
            this.setIconImage(icon);
        } catch (Exception e) {
            System.err.println("Icon image not found.");
        }
    }
    
    public JPanel getPanelParentCard() {
        return this.jPanelParentCard;
    }
    
    private void addPanels() {
        getPanelParentCard().add(itDashboardPanel, "ITDashboard");
        getPanelParentCard().add(ticketsPanel, "Tickets");
        getPanelParentCard().add(viewTicketPanel, "ViewTicket");
        getPanelParentCard().add(accountsPanel, "Accounts");
        getPanelParentCard().add(viewAccountPanel, "ViewAccount");
        getPanelParentCard().add(securityPanel, "Security");
    }
    
    private void addHooverEffectToTabs() {
        addHoverEffect(jLabelITDashboard, jPanelITDashboard);
        addHoverEffect(jLabelEmployeePortal, jPanelEmployeePortal);
        addHoverEffect(jLabelTickets, jPanelTickets);
        //addHoverEffect(jLabelAccess, jPanelAccess);
        addHoverEffect(jLabelAccounts, jPanelAccounts);
        addHoverEffect(jLabelSecurity, jPanelSecurity);
    }

    private void addHoverEffect(JLabel label, JPanel panel) {
        Font originalFont = label.getFont();

        label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel.setBackground(hoverPanelColor);
                label.setFont(originalFont.deriveFont(Font.BOLD));
                label.setForeground(Color.WHITE);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel.setBackground(defaultPanelColor);
                label.setFont(originalFont);
                label.setForeground(Color.BLACK);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWhiteMain = new javax.swing.JPanel();
        jPanelBlueNavigationMenu = new javax.swing.JPanel();
        jPanelTickets = new javax.swing.JPanel();
        jLabelTickets = new javax.swing.JLabel();
        jPanelITDashboard = new javax.swing.JPanel();
        jLabelITDashboard = new javax.swing.JLabel();
        jPanelEmployeePortal = new javax.swing.JPanel();
        jLabelEmployeePortal = new javax.swing.JLabel();
        jPanelAccounts = new javax.swing.JPanel();
        jLabelAccounts = new javax.swing.JLabel();
        jLabelMotorPH = new javax.swing.JLabel();
        jPanelSecurity = new javax.swing.JPanel();
        jLabelSecurity = new javax.swing.JLabel();
        jLabelMorPHLogo = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        jPanelParentCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelWhiteMain.setBackground(new java.awt.Color(255, 255, 255));
        jPanelWhiteMain.setForeground(new java.awt.Color(255, 255, 255));
        jPanelWhiteMain.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanelWhiteMain.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanelWhiteMain.setName(""); // NOI18N
        jPanelWhiteMain.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanelWhiteMain.setLayout(null);

        jPanelBlueNavigationMenu.setBackground(new java.awt.Color(218, 242, 228));
        jPanelBlueNavigationMenu.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanelBlueNavigationMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTickets.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTickets.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTickets.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTickets.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTickets.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTickets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTickets.setText("Tickets");
        jLabelTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTicketsMouseClicked(evt);
            }
        });
        jPanelTickets.add(jLabelTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 40));

        jPanelITDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelITDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelITDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jLabelITDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelITDashboard.setForeground(new java.awt.Color(0, 0, 0));
        jLabelITDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelITDashboard.setText("Dashboard");
        jLabelITDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelITDashboardMouseClicked(evt);
            }
        });
        jPanelITDashboard.add(jLabelITDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelITDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 40));

        jPanelEmployeePortal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmployeePortal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmployeePortal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEmployeePortal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelEmployeePortal.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmployeePortal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmployeePortal.setText("Employee Portal");
        jLabelEmployeePortal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelEmployeePortalMouseMoved(evt);
            }
        });
        jLabelEmployeePortal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEmployeePortalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEmployeePortalMouseEntered(evt);
            }
        });
        jLabelEmployeePortal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelEmployeePortalKeyPressed(evt);
            }
        });
        jPanelEmployeePortal.add(jLabelEmployeePortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelEmployeePortal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 40));

        jPanelAccounts.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAccounts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAccounts.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAccounts.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAccounts.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAccounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAccounts.setText("Accounts");
        jLabelAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAccountsMouseClicked(evt);
            }
        });
        jPanelAccounts.add(jLabelAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 180, 40));

        jLabelMotorPH.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMotorPH.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabelMotorPH.setForeground(new java.awt.Color(33, 105, 84));
        jLabelMotorPH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMotorPH.setText("MotorPH");
        jPanelBlueNavigationMenu.add(jLabelMotorPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 40));

        jPanelSecurity.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSecurity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSecurity.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSecurity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelSecurity.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSecurity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSecurity.setText("Security");
        jLabelSecurity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSecurityMouseClicked(evt);
            }
        });
        jPanelSecurity.add(jLabelSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jPanelBlueNavigationMenu.add(jPanelSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 180, 40));

        jLabelMorPHLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green-motor-logo.png"))); // NOI18N
        jPanelBlueNavigationMenu.add(jLabelMorPHLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 40));

        jLabelLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green-log-out-icon.png"))); // NOI18N
        jLabelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogOutMouseClicked(evt);
            }
        });
        jPanelBlueNavigationMenu.add(jLabelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, -1, -1));

        jPanelWhiteMain.add(jPanelBlueNavigationMenu);
        jPanelBlueNavigationMenu.setBounds(10, 10, 220, 750);

        jPanelParentCard.setBackground(new java.awt.Color(204, 255, 255));
        jPanelParentCard.setMaximumSize(new java.awt.Dimension(1120, 750));
        jPanelParentCard.setMinimumSize(new java.awt.Dimension(1120, 750));
        jPanelParentCard.setPreferredSize(new java.awt.Dimension(1120, 750));
        jPanelParentCard.setLayout(new java.awt.CardLayout());
        jPanelWhiteMain.add(jPanelParentCard);
        jPanelParentCard.setBounds(240, 10, 1120, 750);

        getContentPane().add(jPanelWhiteMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSecurityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSecurityMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Security");
    }//GEN-LAST:event_jLabelSecurityMouseClicked

    private void jLabelAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccountsMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Accounts");
    }//GEN-LAST:event_jLabelAccountsMouseClicked

    private void jLabelEmployeePortalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEmployeePortalKeyPressed

    private void jLabelEmployeePortalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEmployeePortalMouseEntered

    private void jLabelEmployeePortalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalMouseClicked
        // TODO add your handling code here:
        EmployeePortal employeePortal = new EmployeePortal();
        employeePortal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelEmployeePortalMouseClicked

    private void jLabelEmployeePortalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEmployeePortalMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEmployeePortalMouseMoved

    private void jLabelTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTicketsMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "Tickets");
    }//GEN-LAST:event_jLabelTicketsMouseClicked

    private void jLabelITDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelITDashboardMouseClicked
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) getPanelParentCard().getLayout();
        cardLayout.show(getPanelParentCard(), "ITDashboard");
    }//GEN-LAST:event_jLabelITDashboardMouseClicked

    private void jLabelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogOutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to log out?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            LoginPortal loginPortal = new LoginPortal();
            loginPortal.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabelLogOutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAccounts;
    private javax.swing.JLabel jLabelEmployeePortal;
    private javax.swing.JLabel jLabelITDashboard;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelMorPHLogo;
    private javax.swing.JLabel jLabelMotorPH;
    private javax.swing.JLabel jLabelSecurity;
    private javax.swing.JLabel jLabelTickets;
    private javax.swing.JPanel jPanelAccounts;
    private javax.swing.JPanel jPanelBlueNavigationMenu;
    private javax.swing.JPanel jPanelEmployeePortal;
    private javax.swing.JPanel jPanelITDashboard;
    private javax.swing.JPanel jPanelParentCard;
    private javax.swing.JPanel jPanelSecurity;
    private javax.swing.JPanel jPanelTickets;
    private javax.swing.JPanel jPanelWhiteMain;
    // End of variables declaration//GEN-END:variables
}
